Homework2
ok-technopolis-autumn-2022/Alexandrov_Alexey pull request #2
Opened 2022-11-04 19:29 UTC by AlexAndrovSPBSTU

Извиняюсь за столько позднюю сдачу второй домашней работы. Не дружу я с css. Сделал как смог, до идеала бесспорно ещё далеко.

2022-11-05 21:14 UTC, fromanywhere requested changes
Весьма впечатляюще для человека, не дружащего с css

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    background-image: url("../images/select-all.png");
пути поползли

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    width: 20px;
Выравнивание +- удачно (крестик будет накладываться на текст, если строчка будет длинной, но это, допустим, ладно)

Размеры кнопки слишком мелкие — пальцем на телефоне будет сложно попасть. Увеличиваем

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    background-image: url("../images/select-all.png");
Картинки неретиновые, кстати

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    margin-left: 4%;
<img width="819" alt="image" src="https://user-images.githubusercontent.com/1042969/200141362-90a9bcc1-bd49-4af9-b3e0-a5f223c13993.png">


я очень не рекомендую тут использовать проценты — на скрине вот эта дырка слева будет непредсказуемой

текст нужно порезать в многоточие

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    box-shadow: 0px -1px 0px 0px #e6e6e6 inset;
здесь лучше использовать бордер, фигма врет

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    border-radius: 5%;
лучше здесь в пикселях

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    z-index: -1;
видимо, здесь подразумевалось -2

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    width: 20px;
графика, кстати, потерялась

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    box-shadow: 0px -1px 0px 0px #e6e6e6 inset;
аналогично, тут бордер

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    background-image: url(../images/close.png);
Тут лучше не фоновую картинку определять, а расположение самой кнопки (или видимость иным образом). Заодно и фокус тут же можно будет обработать

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    flex-direction: column;
Этот флекс с центрирование расползается по всем студенческим работам, хотя из-за него вот такие спецэффекты 
<img width="295" alt="image" src="https://user-images.githubusercontent.com/1042969/200141529-af6cd54a-ae26-4f1d-84d9-0a5d9cdbe34d.png">

Задайте ему min-width, что ли

2022-11-05 21:14 UTC, fromanywhere commented on style.css
> +    border: 1px solid #EBDFDF;
из-за бордера фильтры прыгают по горизонтали при переключении (бордер нужен, всё верно, но нужно что-то придумать)

2022-11-18 08:06 UTC, fromanywhere commented
<img width="695" alt="image" src="https://user-images.githubusercontent.com/1042969/202651631-9f8ded92-aff7-4bcf-96b8-9b9413ba555c.png">
У меня ломается вся графика, а кнопка удаления не подсвечивается на фокус с клавиатуры

Рвется строка 
<img width="807" alt="image" src="https://user-images.githubusercontent.com/1042969/202651920-6d3c35a6-2ecc-4ef8-82e9-70efb6269101.png">

2022-11-19 22:19 UTC, AlexAndrovSPBSTU commented
Странно, у меня кнопка "выбрать все" отображается стабильно. 
А мы проблему с переполнением строки разве не с подключением JS должны решать?

2022-11-21 07:59 UTC, fromanywhere commented
Нет, проблема с переполнением — это зона ответственности стилей

2022-11-21 12:42 UTC, fromanywhere approved these changes

2022-11-21 12:45 UTC, merged